package com.mindcraft.entity;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "stocks_main_dtls")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class StockListEntity implements Serializable{
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "ticker_symbol", nullable = false, unique = true, length = 10)
    private String tickerSymbol;

    @Column(name = "company_name", nullable = false, length = 255)
    private String companyName;

    @Column(name = "exchange", length = 50)
    private String exchange;

    @Column(name = "sector", length = 100)
    private String sector;

    @Column(name = "current_price", precision = 12)
    private Double currentPrice;
    
    @Column(name = "trd_in_price", precision = 12)
    private Double tradeInPrice;
    
    @Column(name = "no_of_shares")
    private int noOfShares;

    //@Column(name = "market_cap", precision = 18)
    private Double marketCap;

    @Column(name = "volume")
    private Long volume;

    @Column(name = "pe_ratio", precision = 10)
    private Double peRatio;

    @Column(name = "eps", precision = 10)
    private Double eps;

    @Column(name = "dividend_yield", precision = 6)
    private Double dividendYield;

    @Column(name = "last_updated")
    private java.sql.Timestamp lastUpdated;

}

//| Column           | Market Explanation                                                                                                                                             |
//| ---------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- |
//| `ticker_symbol`  | The **unique shorthand symbol** used to identify a company’s stock on the exchange (e.g., `RELIANCE`). Traders and investors use it to quickly find the stock. |
//| `company_name`   | The full **legal name of the company** issuing the stock.                                                                                                      |
//| `exchange`       | The **stock exchange** where the stock is listed (e.g., NSE, BSE). It tells investors where they can trade the stock.                                          |
//| `sector`         | The **industry sector** of the company (e.g., IT, Banking, Energy). Useful for sector-based analysis or comparison.                                            |
//| `current_price`  | The **latest market price** of one share of the stock. It reflects how the market values the company at that moment.                                           |
//| `market_cap`     | The **total market capitalization** — roughly, the total value of all outstanding shares. Used to gauge company size.                                          |
//| `volume`         | The **number of shares traded** during a period (daily volume). Higher volume often indicates higher liquidity.                                                |
//| `pe_ratio`       | **Price-to-Earnings ratio** — shows how much investors are willing to pay per ₹1 of earnings. Used to assess valuation.                                        |
//| `eps`            | **Earnings per Share** — the company’s profit allocated per share. Indicates profitability.                                                                    |
//| `dividend_yield` | The **annual dividend divided by current stock price**, expressed as a percentage. Shows income generated by holding the stock.                                |
//| `last_updated`   | Timestamp of the **most recent update** to the stock data. Indicates how fresh the information is.                                                             |
